[build]
command = "npm run build"
output_dir = ".next"

[env.production]
name = "scholarphile"
pages_build_output_dir = ".next/standalone"

[env.staging]
name = "scholarphile-staging"
pages_build_output_dir = ".next/standalone"
