[build]
command = "npm run build"

[env.production]
name = "scholarphile"
pages_build_output_dir = ".vercel/output/static"

[env.staging]
name = "scholarphile-staging"
pages_build_output_dir = ".vercel/output/static"
