[build]
command = "cd Phile && npm ci --no-audit --no-fund && npm run build"
output_dir = "Phile/out"

[env.production]
name = "scholarphile"
pages_build_output_dir = "Phile/out"

[env.staging]
name = "scholarphile-staging"
pages_build_output_dir = "Phile/out"

