[build]
command = "npm run build"
output_dir = "out"

[env.production]
name = "scholarphile"
pages_build_output_dir = "out"

[env.staging]
name = "scholarphile-staging"
pages_build_output_dir = "out"
